[package]
name = "coffee_maker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-rt = "2.8.0"
log = "0.4.0"
env_logger = "0.10.0"
rand = "0.8.5"
mockall = "0.11.4"
mockall_double = "0.3.0"